### ISSUE TITLE
Country names i18n

### ISSUE THREAD

**Issue by dreamz89** [LouisMazel/maz-ui-3#9]
Sorry to ask already as it is still in progress, but am i able to change all the country names in the dropdown to German? Like in this comment https://github.com/LouisMazel/vue-phone-number-input/issues/77#issuecomment-581003725

**Comment by LouisMazel** [comment]
Hi @dreamz89,

Solved in version **maz-ui@3.0.0-beta.22**

I added a new option property to provide a list of countries `custom-countries-list`
The component will merge the **[initial countries list](https://github.com/LouisMazel/maz-ui-3/blob/master/packages/lib/package/components/MazPhoneNumberInput/utils/countries-name-list-by-iso-code.ts)** with yours. 
So you should use the same keys in your list to override the names.

```vue
<template>
  <MazPhoneNumberInput
    :custom-countries-list="{
      ...
      FR: 'France',
      BE: 'Belgique',
      GE: 'Allemagne',
      US: 'Etats-Unis',
      ...
    }"
  />
</template>
```

Please check the documentation about translations: **[MazPhoneNumberInput](https://louismazel.github.io/maz-ui-3/components/maz-phone-number-input.html#countries-list)**
